# Generated by Django 6.0 on 2026-05-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screening", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidate",
            old_name="resume",
            new_name="resume_file",
        ),
        migrations.RenameField(
            model_name="candidate",
            old_name="ai_score",
            new_name="score",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="detail_score",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="education_score",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="experience_score",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="resume_text_preview",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="skill_match",
        ),
        migrations.AddField(
            model_name="candidate",
            name="matched_skills",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="resume_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="email",
            field=models.EmailField(default="noemail@resume.com", max_length=254),
        ),
    ]
